const seed=[
 {id:1,title:'Send revised launch copy to Maya',owner:'You',due:'Today',risk:true,evidence:'“I told her I’d send a revised draft by Friday.”',status:'open'},
 {id:2,title:'Confirm legal review scope',owner:'You',due:'Tomorrow',risk:true,evidence:'“Maya said the launch copy needs legal review.”',status:'open'},
 {id:3,title:'Move analytics dashboard to next sprint',owner:'You',due:'Oct 6',risk:false,evidence:'“We agreed the analytics dashboard can wait until next sprint.”',status:'open'},
 {id:4,title:'Share onboarding checklist with team',owner:'You',due:'Oct 9',risk:false,evidence:'From planning notes: “I’ll share the checklist next week.”',status:'open'},
 {id:5,title:'Book customer research interviews',owner:'You',due:'Oct 12',risk:false,evidence:'From weekly review: “I’ll book the interviews by the 12th.”',status:'open'},
 {id:6,title:'Send Q3 retrospective',owner:'You',due:'Sep 28',risk:false,evidence:'From standup transcript.',status:'done'}];
let items=JSON.parse(localStorage.getItem('promiseos-items')||'null')||seed; let filter='all';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const save=()=>localStorage.setItem('promiseos-items',JSON.stringify(items));
function toast(msg){const t=$('#toast');t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',2800)}
function setAI(state){$('#aiStatus').textContent=`NEMOTRON • ${state}`;$('#nemotronState').textContent=state;$('#coreState').textContent=state==='THINKING'?'REASONING':state==='DEMO MODE'?'DEMO READY':'CONNECTED'}
async function pipeline(active=true){const p=$('#pipeline'),stages=$$('.pipe');if(!active){stages.forEach(s=>s.className='pipe');p.classList.remove('visible');return}p.classList.add('visible');for(let i=0;i<stages.length-1;i++){stages[i].classList.add('active');await new Promise(r=>setTimeout(r,160));stages[i].classList.replace('active','done')}stages.at(-1).classList.add('active')}
function esc(s){return String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function render(){const open=items.filter(i=>i.status==='open'), risk=open.filter(i=>i.risk);$('#openN').textContent=open.length;$('#riskN').textContent=risk.length;$('#count').textContent=risk.length; $('#doneN').textContent=12+items.filter(i=>i.status==='done'&&!seed.find(x=>x.id===i.id)).length;
 $('#attention').innerHTML=risk.slice(0,3).map(card).join('')||'<p class="sub">No at-risk promises. Your future self approves.</p>';
 const list=items.filter(i=>filter==='all'||filter==='risk'&&i.risk||filter==='open'&&i.status==='open'||filter==='done'&&i.status==='done');$('#ledgerList').innerHTML=list.map(ledger).join('');}
function card(i){return `<article class="card"><span class="dot ${i.risk?'':'safe'}"></span><div><h4>${esc(i.title)}</h4><p>${esc(i.owner)} · Evidence linked</p></div><span class="due">${esc(i.due)}</span></article>`}
function ledger(i){return `<article class="ledgeritem ${i.status==='done'?'done':''}" data-id="${i.id}"><span class="dot ${i.risk?'':'safe'}"></span><div><h4>${esc(i.title)}</h4><p>Owner: ${esc(i.owner)} · Due ${esc(i.due)} · ${i.risk?'At risk':'On track'}</p></div>${i.status==='open'?'<button class="complete">Mark done</button>':'<button>Completed</button>'}<div class="evidence"><b>Evidence</b> — ${esc(i.evidence)}</div></article>`}
function go(view){$$('.view').forEach(x=>x.classList.remove('visible'));$(`#${view}`).classList.add('visible');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#title').textContent={today:'Your attention has a budget.',ledger:'Remembering is not the same as knowing.',capture:'Capture first. Organize later.',ask:'Memory, with receipts.'}[view];$('#crumb').textContent=view==='today'?'WEDNESDAY, OCT 1':view.toUpperCase()}
$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-goto]').forEach(b=>b.onclick=()=>go(b.dataset.goto));
$('#ledgerList').onclick=e=>{const article=e.target.closest('.ledgeritem');if(!article)return;const item=items.find(i=>i.id==article.dataset.id);if(e.target.classList.contains('complete')){item.status='done';item.risk=false;save();render();toast('Promise completed — ledger updated.');return}article.classList.toggle('expanded')};
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');filter=b.dataset.filter;render()});
function settings(){return {apiKey:sessionStorage.getItem('nebius-key')||'',model:sessionStorage.getItem('nebius-model')||$('#model').value,endpoint:sessionStorage.getItem('nebius-endpoint')||$('#endpoint').value}}
async function call(messages,maxTokens=1200){const s=settings();if(!s.apiKey)throw Error('Demo mode is on — add your Nebius Token Factory key in Settings for live Nemotron reasoning.');setAI('THINKING');await pipeline();try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...s,messages,maxTokens})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not reach Nebius');setAI('CONNECTED');return d.content}finally{await new Promise(r=>setTimeout(r,350));pipeline(false)}}
function demoExtract(text){const result=[];const lower=text.toLowerCase();if(lower.includes('maya')||lower.includes('draft'))result.push({title:'Send revised launch copy to Maya',owner:'You',due:'Friday',risk:false,evidence:text.slice(0,170),status:'open'});if(lower.includes('legal'))result.push({title:'Confirm legal review scope',owner:'You',due:'Unspecified',risk:false,evidence:text.slice(0,170),status:'open'});if(!result.length)result.push({title:'Follow up on captured note',owner:'You',due:'Unspecified',risk:false,evidence:text.slice(0,170),status:'open'});return result}
function proposals(found){const box=$('#proposals');box.innerHTML='<p class="eyebrow">PROPOSED — HUMAN APPROVAL REQUIRED</p>'+found.map((i,n)=>`<div class="proposal" data-p="${n}"><div><b>${esc(i.title)}</b><small>Owner: ${esc(i.owner||'You')} · Due: ${esc(i.due||'Unspecified')} · Evidence retained</small></div><div class="proposeactions"><button class="dismiss">Dismiss</button><button class="approve">Approve</button></div></div>`).join('');box.onclick=e=>{const row=e.target.closest('.proposal');if(!row)return;const x=found[row.dataset.p];if(e.target.classList.contains('approve')){x.id=Date.now()+Number(row.dataset.p);x.status='open';items.unshift(x);save();render();row.remove();toast('Approved and added to your ledger.')}else if(e.target.classList.contains('dismiss'))row.remove()}}
$('#extract').onclick=async()=>{const note=$('#note').value.trim();if(!note)return toast('Paste a note first.');const b=$('#extract');b.textContent='Extracting…';try{let found;if(settings().apiKey){const out=await call([{role:'system',content:'You extract commitments from notes. Return ONLY a JSON array. Each item has title, owner, due, risk(boolean), evidence (short verbatim quote), status:"open". Do not invent commitments.'},{role:'user',content:note}]);found=JSON.parse(out.replace(/```json|```/g,'').trim())}else{await new Promise(r=>setTimeout(r,550));found=demoExtract(note)}proposals(found);toast(settings().apiKey?'Nemotron extracted proposals.':'Demo proposals created — add key for live Nemotron.')}catch(e){toast(e.message)}finally{b.textContent='✦ Extract commitments'}};
$('#brief').onclick=async()=>{const b=$('#brief');b.textContent='Thinking…';try{let plan;if(settings().apiKey){plan=await call([{role:'system',content:'You are a concise personal operations planner. From these commitments, give a 3-step plan for today. Prioritize consequences, cite commitment titles, and never invent details.'},{role:'user',content:JSON.stringify(items.filter(i=>i.status==='open'))}],500)}else plan='1. Send Maya the revised draft first — it has a concrete deadline and an external dependency.\n2. Confirm the legal-review scope so the launch copy does not stall.\n3. Schedule 20 minutes to move the dashboard decision into next sprint.';toast(plan); }catch(e){toast(e.message)}finally{b.textContent='✦ Generate focused plan'}};
$('#askForm').onsubmit=async e=>{e.preventDefault();const q=$('#question').value.trim();if(!q)return;const chat=$('#chat');chat.insertAdjacentHTML('beforeend',`<div class="bubble user">${esc(q)}</div>`);$('#question').value='';const response=document.createElement('div');response.className='bubble assistant streaming';response.textContent='Retrieving the memories that matter…';chat.append(response);try{let ans;if(settings().apiKey)ans=await call([{role:'system',content:'Answer ONLY from this commitment ledger. Cite evidence quotes in your answer. If unsupported say you do not know. Ledger: '+JSON.stringify(items)},{role:'user',content:q}],700);else{setAI('DEMO MODE');await pipeline();await new Promise(r=>setTimeout(r,500));ans=q.toLowerCase().includes('focus')?'Start with “Send revised launch copy to Maya.” It is due today and unblocks legal review. I recommend one protected 25-minute sprint, then send the draft before checking messages.':q.toLowerCase().includes('promise')?'This week you promised Maya a revised launch-copy draft by Friday and committed to confirming the legal-review scope. Both are in your evidence-backed ledger.':'Your most valuable unfinished commitment is the launch-copy draft. It has an external owner, a clear deadline, and a linked legal-review dependency.';setAI('DEMO MODE');pipeline(false)}response.textContent=ans;response.classList.remove('streaming');chat.scrollTop=chat.scrollHeight}catch(e){response.textContent=e.message;response.classList.remove('streaming');setAI('OFFLINE')} };
$('#settings').onclick=()=>{$('#apiKey').value=settings().apiKey;$('#model').value=settings().model;$('#endpoint').value=settings().endpoint;$('#modal').showModal()};$('.close').onclick=()=>$('#modal').close();$('#saveSettings').onclick=()=>{sessionStorage.setItem('nebius-key',$('#apiKey').value.trim());sessionStorage.setItem('nebius-model',$('#model').value.trim());sessionStorage.setItem('nebius-endpoint',$('#endpoint').value.trim());$('#modal').close();toast('Session settings saved locally.');};$('#demo').onclick=()=>toast('Demo mode lets judges explore without credentials. Add a key for live Nemotron.');
let seconds=1500,focusTimer=null;function paintFocus(){const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');$('#focusTime').textContent=`${m}:${s}`;$('#overlayTimer').textContent=`${m}:${s}`;$('#focusLabel').textContent=focusTimer?'Protecting attention…':'Ready when you are'}function startFocus(){document.body.classList.add('focused');$('#focusState').textContent='ACTIVE';$('#galaxy').classList.add('focus-galaxy');focusTimer=setInterval(()=>{if(seconds>0){seconds--;paintFocus()}else{clearInterval(focusTimer);focusTimer=null;document.body.classList.remove('focused');$('#focusState').textContent='COMPLETE';$('#signalN').textContent='88';$('#signalText').textContent='Focus session completed. Momentum is rising.';toast('Focus complete — your attention did its job.')}},1000);$('#focus').textContent='Ⅱ Pause focus sprint';$('#overlayPause').textContent='Pause sprint';paintFocus();toast('25-minute focus sprint started.')}function pauseFocus(){clearInterval(focusTimer);focusTimer=null;$('#focusState').textContent='PAUSED';$('#focus').textContent='◷ Resume focus sprint';$('#overlayPause').textContent='Resume sprint';paintFocus();toast('Focus sprint paused.')}$('#focus').onclick=()=>focusTimer?pauseFocus():startFocus();$('#overlayPause').onclick=()=>focusTimer?pauseFocus():startFocus();$('#exitFocus').onclick=()=>{pauseFocus();document.body.classList.remove('focused');$('#galaxy').classList.remove('focus-galaxy');$('#focusState').textContent='IDLE'};$('#soundToggle').onclick=()=>{const b=$('#soundToggle');b.textContent=b.textContent==='Sound off'?'Sound on':'Sound off'};
function openMemory(raw){const [title,type,time,content]=raw.split('|');$('#memoryTitle').textContent=title;$('#memoryMeta').textContent=`${type}  ·  ${time}  ·  ID ${Math.random().toString(36).slice(2,8).toUpperCase()}`;$('#memoryContent').textContent=content;$('#memoryModal').showModal()}$$('[data-memory]').forEach(n=>n.onclick=()=>openMemory(n.dataset.memory));$$('.memoryClose').forEach(n=>n.onclick=()=>$('#memoryModal').close());$('#galaxy').addEventListener('mousemove',e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;e.currentTarget.style.transform=`rotateY(${x*7}deg) rotateX(${-y*5}deg)`});$('#galaxy').addEventListener('mouseleave',e=>e.currentTarget.style.transform='');$$('.quickprompts button').forEach(b=>b.onclick=()=>{$('#question').value=b.textContent;$('#askForm').requestSubmit()});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();go('ask');$('#question').focus()}if(e.key==='Escape'&&document.body.classList.contains('focused'))$('#exitFocus').click()});paintFocus();render();
